services:
  autossh:
    build: .
    volumes:
      - ~/.ssh:/home/myuser/.ssh:ro
      - ./config.yaml:/etc/autossh/config.yaml:ro
    environment:
      - AUTOSSH_GATETIME=0
    network_mode: "host"