services:
  autossh:
    build:
      context: .
      dockerfile: Dockerfile.custom
      args:
        UID: ${HOST_UID:-1000}  # Use HOST_UID or default to 1000
        GID: ${HOST_GID:-1000}  # Use HOST_GID or default to 1000
    image: custom-autossh-tunnel:latest
    volumes:
      - ~/.ssh:/home/myuser/.ssh:ro
      - ./config.yaml:/etc/autossh/config.yaml:ro
    environment:
      - AUTOSSH_GATETIME=0
    network_mode: "host"
    restart: always